
#DATASOURCE


spring:
  application:
    name: Health Appointment API - Backend
    version: v1.0.0
    since: 06/07/2023
    author: Felipe Lima
  data:
      mongodb:
#        user: mongo
#        password: mongo
#        uri: mongodb://host:27017/ha_db
#        host: 127.0.0.1
#        port: 27017
#        database: ha_db

        uri: mongodb://localhost:27017/ha_db